frontend/__init__.py
from flask import Flask
from frontend.config import Config


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    from frontend.dashboard.routes import dash
    app.register_blueprint(dash)

    return app

frontend/dashboard/routes.py
from flask import Blueprint, render_template, current_app
import requests
from titlecase import titlecase

dash = Blueprint('dash', __name__)


@dash.route('/', methods=['GET'])
def home():
    return render_template('home.html', supported=current_app.config['SUPPORTED'])


@dash.route('/emp/<website>', methods=['GET'])
def show_emp(website):
    website = website.upper()
    if website == "TWILIO" or website == "SQUARESPACE" or website == "PINTEREST" or website == "JDPOWER"\
            or website == "THETRADEDESK" or website == "HARRYS":
        raw_data = requests.get(current_app.config[f'{website}_EMP_URL'])
        data = raw_data.json()
        final_list = []
        i = 1
        for location in data['offices']:
            for dept in location['departments']:
                for job in dept['jobs']:
                    final_list.append({
                        'id': i,
                        'title': job['title'],
                        'location': location['location'],
                        'department': dept['name'],
                        'url': job['absolute_url']
                    })
                    i += 1
        return render_template('all_emp.html', data=final_list, company=titlecase(website))
    elif website == "AIRBNB":
        raw_data = requests.get(current_app.config[f'{website}_EMP_URL'])
        data = raw_data.json()
        final_list = []
        departments = {}
        for dept in data['departments']:
            departments[dept['id']] = dept['name']
        i = 1
        for job in data['jobs']:
            final_list.append({
                'id': i,
                'title': job['title'],
                'location': job['location'],
                'department': departments[job['deptId']],
                'url': f"https://careers.airbnb.com/positions/{job['id']}"
            })
            i += 1
        return render_template('all_emp.html', data=final_list, company=titlecase(website))
    elif website == "YEXT":
        raw_data = requests.get(current_app.config[f'{website}_EMP_URL'])
        data = raw_data.json()
        final_list = []
        i = 1
        for dept in data['departments']:
            for job in dept['jobs']:
                final_list.append({
                    'id': i,
                    'title': job['title'],
                    'location': job['location']['name'],
                    'department': job['metadata'][0]['value'],
                    'url': job['absolute_url']
                })
                i += 1
        return render_template('all_emp.html', data=final_list, company=titlecase(website))
    elif website == "HUBSPOT":
        raw_data = requests.get(current_app.config[f'{website}_EMP_URL'])
        data = raw_data.json()
        final_list = []
        i = 1
        for job in data:
            final_list.append({
                'id': i,
                'title': job['title'],
                'location': job['offices'],
                'department': job['department'],
                'url': job['appUrl']
            })
            i += 1
        return render_template('all_emp.html', data=final_list, company=titlecase(website))
    else:
        return render_template('all_emp.html', data=[], company=titlecase(website))

frontend/templates/all_emp.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Empape</title>

    <!-- Bootstrap Core CSS -->
    <link href="../../static/main/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="../../static/main/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../../static/main/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="../../static/main/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('dash.home') }}">Empape</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <a href="{{ url_for('dash.home') }}"><button type="button" class="btn">Home</button></a>
            </ul>
            <!-- /.navbar-top-links -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    {% with messages = get_flashed_messages(with_categories = true) %}
            	        {% if messages %}
	                        {% for category, message in messages %}
                	            <div class = 'alert alert-{{ category }}'>
	                                {{ message }}
	                            </div>
                            {% endfor %}
	                    {% endif %}
                    {% endwith %}
                    <h1 class="page-header">Jobs at {{ company }}</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bar-chart-o fa-fw"></i> All Jobs
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Title</th>
                                        <th scope="col">Location</th>
                                        <th scope="col">Department</th>
                                        <th scope="col">Apply</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if data|length != 0 %}
                                        {% for emp in data %}
                                            <tr>
                                                <th scope="row">{{ emp['id'] }}</th>
                                                <td>{{ emp['title'] }}</td>
                                                <td>{{ emp['location'] }}</td>
                                                <td>{{ emp['department'] }}</td>
                                                <td><a href="{{ emp['url'] }}">Click Here</a></td>
                                            </tr>
                                        {% endfor %}
                                    {% else %}
                                        <td colspan="5">Sorry, no jobs available at this company at the moment!</td>
                                    {% endif %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-8 -->
            </div>
            <!-- /.row -->
            <script>
            var distance = 5;
            // Update the count down every 1 second
            var x = setInterval(function() {

                distance -= 1;

                // If the count down is finished, write some text
                if (distance < 0) {
                  window.location.reload(true)
                }
            }, 1000);
            </script>
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="../../static/main/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../../static/main/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="../../static/main/vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="../../static/main/dist/js/sb-admin-2.js"></script>

</body>

</html>

frontend/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Empape | Companies</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="../../static/log/images/icons/favicon.ico"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="../../static/log/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="../../static/log/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="../../static/log/fonts/iconic/css/material-design-iconic-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="../../static/log/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="../../static/log/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="../../static/log/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="../../static/log/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="../../static/log/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="../../static/log/css/util.css">
    <link rel="stylesheet" type="text/css" href="../../static/log/css/main.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!--===============================================================================================-->
</head>
<body>

<div class="limiter">
    <div class="container-login100" style="background-image: url('../../static/log/images/bg-01.jpg');">
        <div class="wrap-login100">
                <span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

            <span class="login100-form-title p-b-34 p-t-27">
						Select Company
					</span>
            {% with messages = get_flashed_messages(with_categories = true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class='alert alert-{{ category }}'>
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
            <div class="row">
                <div class="col-lg-4">
                    {% for i in range(0, (supported|length // 3 + (1 if supported|length % 3 >= 1 else 0))) %}
                    <div class="container-login100-form-btn p-t-10">
                        <a href="/emp/{{ supported[i] }}">
                            <button class="login100-form-btn">
                                {{ supported[i] }}
                            </button>
                        </a>
                    </div>
                    {% endfor %}
                </div>
                <div class="col-lg-4">
                    {% for i in range((supported|length // 3 + (1 if supported|length % 3 >= 1 else 0)),
                    (2 * (supported|length // 3) + (2 if supported|length % 3 >= 2 else 0))) %}
                    <div class="container-login100-form-btn p-t-10">
                        <a href="/emp/{{ supported[i] }}">
                            <button class="login100-form-btn">
                                {{ supported[i] }}
                            </button>
                        </a>
                    </div>
                    {% endfor %}
                </div>
                <div class="col-lg-4">
                    {% for i in range((2 * (supported|length // 3) + (2 if supported|length % 3 >= 2 else 0)),
                    (supported|length)) %}
                    <div class="container-login100-form-btn p-t-10">
                        <a href="/emp/{{ supported[i] }}">
                            <button class="login100-form-btn">
                                {{ supported[i] }}
                            </button>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

<!--===============================================================================================-->
<script src="../../static/log/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
<script src="../../static/log/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
<script src="../../static/log/vendor/bootstrap/js/popper.js"></script>
<script src="../../static/log/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
<script src="../../static/log/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="../../static/log/vendor/daterangepicker/moment.min.js"></script>
<script src="../../static/log/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
<script src="../../static/log/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
<script src="../../static/log/js/main.js"></script>

</body>
</html>